name: nextjs-cloud-run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CLOUD_RUN_REGION: ${{ secrets.GCP_REGION }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

jobs:
  # tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Build test compose
  #       run: npm run test

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure docker auth
        run: gcloud auth configure-docker --quiet

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and tag image
        run: docker build . -t $IMAGE_NAME

      - name: Push image to GCR
        run: docker push $IMAGE_NAME

      - name: Deploy
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region $CLOUD_RUN_REGION --platform managed
